version: 2
jobs:
  boards:
    docker:
      - image: georgehopkins/tock
        environment:
          TERM: xterm
          RUST_BACKTRACE: 1
    steps:
      - checkout
      - run: |
          make allboards V=1 || (cd $(find /usr/local/cargo/git/checkouts/ -maxdepth 2 -mindepth 2 -type d) && pwd && git submodule init && git submodule update)
          make allboards V=1
  examples:
    docker:
      - image: georgehopkins/tock
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: |
          cd userland/examples
          ./build_all.sh
  libraries:
    docker:
      - image: georgehopkins/tock
    steps:
      - checkout
      - run: apt-get update && apt-get install -y unzip
      - run: |
          git submodule sync
          git submodule update --init
      - run: |
          cd userland/libnrfserialization
          ./create_libnrfserialization.sh
          find build/ -type f -not -name '*.a' -delete
      - store_artifacts:
          path: userland/libnrfserialization/build
      - store_artifacts:
          path: userland/libnrfserialization/headers.tar.gz
      - run: |
          cd userland/lua53
          make
          find build/ -type f -not -name '*.a' -delete
      - store_artifacts:
          path: userland/lua53/build
workflows:
  version: 2
  build:
    jobs:
      - boards
      - examples
      - libraries
